name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Créer .env.dev à partir des secrets
        run: |
          touch .env.dev
          echo "secretOrPrivateKey=${{ secrets.secretOrPrivateKey }}" >> .env.dev
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env.dev
          echo "PORT=${{ secrets.PORT }}" >> .env.dev
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env.dev
          echo "AI_SERVICE_URL=${{ secrets.AI_SERVICE_URL }}" >> .env.dev
          echo "AUTH_SERVICE_URL=${{ secrets.AUTH_SERVICE_URL }}" >> .env.dev
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env.dev


      - name: Install dependencies
        if: hashFiles('package.json') != ''
        run: npm install

      - name: Run tests
        if: hashFiles('src/tests/**') != ''
        run: npm test -- --watchAll=false

      - name: Set lowercase Docker user
        run: echo "DOCKER_USER=$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV


      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ env.DOCKER_USER }}/bdd:latest .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ env.DOCKER_USER }}/bdd:latest
